# Generated by Django 5.0.4 on 2024-06-05 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('admin_name', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('user_id', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
