# Generated by Django 5.0.4 on 2024-05-19 16:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_name', models.CharField(blank=True, max_length=20)),
                ('admin_password', models.CharField(blank=True, max_length=20)),
                ('admin_email', models.EmailField(blank=True, max_length=50)),
                ('admin_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
