# Generated by Django 5.0.4 on 2024-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='admin_password',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='post_date',
        ),
        migrations.AddField(
            model_name='administrator',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
