# Generated by Django 5.0.4 on 2024-05-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_administrator_admin_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='admin_email',
            new_name='email',
        ),
    ]
