# Generated by Django 5.0.4 on 2024-05-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_rename_admin_email_administrator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
