# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test_frontend
  - test_backend

test:
  stage: test_frontend
  image: node:current-alpine3.16
  script:
    - npm install
    - npm test -- --watchAll=false
  only:
    - Test
  tags:
    - nccutrial_frontend

test:
  stage: test_backend
  script:
    - sudo docker compose up --build
    - sudo docker exec -it backend-backend-1 "/usr/local/bin/python manage.py test"
    - sudo docker compose down
  only:
    - Test
  tags:
    - nccutrial_backend

