# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test_frontend
  - test_backend

test_frontend:
  stage: test_frontend
  image: node:current-alpine3.16
  script:
    - cd ./xdpets
    - npm install
    - npm test -- --watchAll=false
  only:
    - Test
  when: always
  tags:
    - nccutrial_frontend

test_backend:
  stage: test_backend
  script:
    - cd ./backend
    - cp /home/gitlab-runner/.env .
    - docker compose up --build -d
    - sleep 30
    - docker exec -i backend-backend-1 bash -c "/usr/local/bin/python /app/manage.py test"
    - docker compose down
  only:
    - Test
  when: always
  tags:
    - nccutrial_backend
