version: '3'

services:
  frontend:
    build: ./frontend
    image: $CI_REGISTRY_USER/frontend:$CI_COMMIT_REF_SLUG
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: $CI_REGISTRY_USER/backend:$CI_COMMIT_REF_SLUG
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    image: $CI_REGISTRY_USER/celery:$CI_COMMIT_REF_SLUG
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: ./backend
    command: celery -A backend beat --loglevel=info
    image: $CI_REGISTRY_USER/celery-beat:$CI_COMMIT_REF_SLUG
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # migrate:
  #   build: ./backend
  #   command: python manage.py makemigrations && python manage.py migrate
  #   volumes:
  #     - ./backend:/code