version: '3'

services:
  frontend:
    build: ./frontend
    image: xdpets_1/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: xdpets_1/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    image: xdpets_1/celery:latest
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: ./backend
    image: xdpets_1/celery-beat:latest
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  migrate:
    build: ./backend
    image: xdpets_1/migrate:latest
    command: python manage.py makemigrations && python manage.py migrate
    volumes:
      - ./backend:/code