# Generated by Django 5.0.4 on 2024-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
