# Generated by Django 5.0.4 on 2024-05-19 16:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('breed', models.CharField(blank=True, max_length=15, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('coat_color', models.CharField(blank=True, max_length=10, null=True)),
                ('ligated', models.BooleanField(blank=True, null=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', models.TextField(blank=True, null=True)),
                ('legal', models.BooleanField(blank=True, null=True)),
                ('ownerId', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
