# Generated by Django 5.0.4 on 2024-05-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_alter_users_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("breed", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.users"
                    ),
                ),
            ],
        ),
    ]
