# Generated by Django 5.0.4 on 2024-06-01 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="legal",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="post_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="petimage",
            name="image",
            field=models.ImageField(upload_to="media/pet_images/"),
        ),
    ]
