# Generated by Django 5.0.4 on 2024-05-12 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
        ("user", "0002_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="user.users",
            ),
        ),
    ]
