# Generated by Django 5.0.4 on 2024-06-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_alter_pet_legal_alter_pet_post_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petimage",
            name="image",
            field=models.ImageField(upload_to="pet_images/"),
        ),
    ]
